<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\uploads\audio\989aa1a3-8c31-4ce0-a463-dfc10736b8cd_recording.wav" />
    <Content Remove="wwwroot\uploads\audio\9924417b-2b1a-4611-9b90-220293a4f9ce_recording.wav" />
    <Content Remove="wwwroot\uploads\audio\c5347a96-3df0-4534-b482-638a912fe416_recording.wav" />
    <Content Remove="wwwroot\uploads\audio\c53a07d3-6196-4875-b141-690bcfb684da_recording.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\uploads\audio\989aa1a3-8c31-4ce0-a463-dfc10736b8cd_recording.wav" />
    <None Include="wwwroot\uploads\audio\9924417b-2b1a-4611-9b90-220293a4f9ce_recording.wav" />
    <None Include="wwwroot\uploads\audio\c5347a96-3df0-4534-b482-638a912fe416_recording.wav" />
    <None Include="wwwroot\uploads\audio\c53a07d3-6196-4875-b141-690bcfb684da_recording.wav" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AudioStorage\" />
    <Folder Include="wwwroot\pdfs\" />
  </ItemGroup>

</Project>
